<a href="https://colab.research.google.com/github/Aldistwn29/DatePandas/blob/main/DataPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from datetime import datetime
import datetime as dt
import matplotlib.pyplot as plt

In [ ]:
data_set = sns.load_dataset("taxis")

In [ ]:
data_set.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [ ]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

# Mengubah string menjadi date

In [ ]:
date_set = sns.load_dataset("taxis")
date_set["pickup"] = pd.to_datetime(date_set["pickup"])
date_set["dropoff"] = pd.to_datetime(date_set["dropoff"])
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [ ]:
date_set["dropoff"].dt.month.unique()

array([3, 4, 2])

In [ ]:
# mendefinisikan time zone mengconvert
date_set["dropoff"].dt.tz_localize("UTC").dt.tz_convert("Asia/Jakarta")

0      2019-03-24 03:27:24+07:00
1      2019-03-04 23:19:00+07:00
2      2019-03-28 01:00:25+07:00
3      2019-03-10 08:49:51+07:00
4      2019-03-30 20:37:14+07:00
                  ...
6428   2019-03-31 16:55:27+07:00
6429   2019-04-01 01:34:23+07:00
6430   2019-03-24 06:14:25+07:00
6431   2019-03-04 17:14:29+07:00
6432   2019-03-14 02:48:02+07:00
Name: dropoff, Length: 6433, dtype: datetime64[ns, Asia/Jakarta]

In [ ]:
# menggubah menjadi priode
date_set["pickup"].dt.to_period("1m")

0       2019-03
1       2019-03
2       2019-03
3       2019-03
4       2019-03
         ...
6428    2019-03
6429    2019-03
6430    2019-03
6431    2019-03
6432    2019-03
Name: pickup, Length: 6433, dtype: period[M]

In [ ]:
(date_set["pickup"] - date_set["dropoff"])

0      -1 days +23:53:45
1      -1 days +23:52:55
2      -1 days +23:52:36
3      -1 days +23:34:08
4      -1 days +23:50:28
              ...
6428   -1 days +23:56:26
6429   -1 days +23:03:37
6430   -1 days +23:40:53
6431   -1 days +23:54:56
6432   -1 days +23:43:20
Length: 6433, dtype: timedelta64[ns]

In [ ]:
(date_set["dropoff"] - date_set["pickup"]).dt.seconds //60

0        6
1        7
2        7
3       25
4        9
        ..
6428     3
6429    56
6430    19
6431     5
6432    16
Length: 6433, dtype: int64

In [ ]:
date_set["dropoff"] + pd.to_timedelta(4 , unit= "H")

0      2019-03-24 00:27:24
1      2019-03-04 20:19:00
2      2019-03-27 22:00:25
3      2019-03-10 05:49:51
4      2019-03-30 17:37:14
               ...
6428   2019-03-31 13:55:27
6429   2019-03-31 22:34:23
6430   2019-03-24 03:14:25
6431   2019-03-04 14:14:29
6432   2019-03-13 23:48:02
Name: dropoff, Length: 6433, dtype: datetime64[ns]

In [ ]:
# rata yg ada di data dropoff
date_set["dropoff"].mean()

Timestamp('2019-03-16 08:45:49.491217408')

In [ ]:
date_set.groupby("payment").resample("1d", on = "pickup").agg({"passengers" : "max",
                                                              "tip" : "max"})

                        passengers    tip
payment     pickup
cash        2019-02-28           1   0.00
            2019-03-01           6   0.00
            2019-03-02           6   0.00
            2019-03-03           6   0.00
            2019-03-04           6   0.00
...                            ...    ...
credit card 2019-03-27           6  16.39
            2019-03-28           6  20.80
            2019-03-29           6  23.19
            2019-03-30           6  20.08
            2019-03-31           6  12.21

[63 rows x 2 columns]

In [ ]:
# membuat data_set baru dengan fungsi leg (-) dan leag(+)
date_set["pickup_hmin1"] = date_set["pickup"].shift(1)

In [ ]:
date_set.filter(like = "pickup")

,pickup,pickup_zone,pickup_borough,pickup_hmin1
0,2019-03-23 20:21:09,Lenox Hill West,Manhattan,NaT
1,2019-03-04 16:11:55,Upper West Side South,Manhattan,2019-03-23 20:21:09
2,2019-03-27 17:53:01,Alphabet City,Manhattan,2019-03-04 16:11:55
3,2019-03-10 01:23:59,Hudson Sq,Manhattan,2019-03-27 17:53:01
4,2019-03-30 13:27:42,Midtown East,Manhattan,2019-03-10 01:23:59
...,...,...,...,...
6428,2019-03-31 09:51:53,East Harlem North,Manhattan,2019-03-23 18:26:09
6429,2019-03-31 17:38:00,Jamaica,Queens,2019-03-31 09:51:53
6430,2019-03-23 22:55:18,Crown Heights North,Brooklyn,2019-03-31 17:38:00
6431,2019-03-04 10:09:25,East New York,Brooklyn,2019-03-23 22:55:18
6432,2019-03-13 19:31:22,Boerum Hill,Brooklyn,2019-03-04 10:09:25

In [ ]:
# membandingkan anatara series pickup_hmin1 dan pickup
date_set["pickup"] - date_set["pickup_hmin1"]

0                     NaT
1      -20 days +19:50:46
2        23 days 01:41:06
3      -18 days +07:30:58
4        20 days 12:03:43
              ...
6428      7 days 15:25:44
6429      0 days 07:46:07
6430    -8 days +05:17:18
6431   -20 days +11:14:07
6432      9 days 09:21:57
Length: 6433, dtype: timedelta64[ns]

In [ ]:
# menggrutukan data
date_set.sort_values("pickup")

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,pickup_hmin1
6203,2019-02-28 23:29:03,2019-02-28 23:32:35,1,0.90,5.0,0.00,0.0,6.30,green,cash,Old Astoria,Long Island City/Queens Plaza,Queens,Queens,2019-03-31 09:43:27
884,2019-03-01 00:03:29,2019-03-01 00:13:32,3,2.16,10.0,2.00,0.0,15.80,yellow,credit card,Lincoln Square East,Upper East Side North,Manhattan,Manhattan,2019-03-16 22:58:35
2882,2019-03-01 00:08:32,2019-03-01 00:29:47,3,7.35,22.5,1.00,0.0,27.30,yellow,credit card,East Chelsea,Mott Haven/Port Morris,Manhattan,Bronx,2019-03-27 18:52:14
4212,2019-03-01 00:15:53,2019-03-01 00:47:58,1,7.00,25.5,7.30,0.0,36.60,yellow,credit card,West Village,Astoria,Manhattan,Queens,2019-03-21 18:40:05
661,2019-03-01 00:29:22,2019-03-01 00:32:48,4,0.74,4.5,1.00,0.0,9.30,yellow,credit card,Meatpacking/West Village West,Meatpacking/West Village West,Manhattan,Manhattan,2019-03-13 12:15:18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220,2019-03-31 22:13:37,2019-03-31 22:22:50,1,1.00,7.5,0.70,0.0,12.00,yellow,credit card,SoHo,Lower East Side,Manhattan,Manhattan,2019-03-08 20:07:54
2849,2019-03-31 22:32:27,2019-03-31 22:34:45,1,0.40,3.5,1.45,0.0,8.75,yellow,credit card,Midtown North,Lincoln Square East,Manhattan,Manhattan,2019-03-25 10:46:05
542,2019-03-31 22:51:53,2019-03-31 22:55:10,1,0.67,4.5,1.66,0.0,9.96,yellow,credit card,West Village,Meatpacking/West Village West,Manhattan,Manhattan,2019-03-21 22:40:43
4067,2019-03-31 23:15:03,2019-03-31 23:27:12,1,3.03,11.5,3.82,0.0,19.12,yellow,credit card,Midtown East,Upper West Side South,Manhattan,Manhattan,2019-03-01 22:57:44
591,2019-03-31 23:43:45,2019-04-01 00:13:58,5,12.25,37.0,0.00,0.0,40.80,yellow,cash,LaGuardia Airport,Williamsburg (South Side),Queens,Brooklyn,2019-03-14 16:22:50

In [ ]:
# menggunakan rolling
date_set.sort_values("pickup")["passengers"].rolling(3).max()

6203    NaN
884     NaN
2882    3.0
4212    3.0
661     4.0
       ...
4220    1.0
2849    1.0
542     1.0
4067    1.0
591     5.0
Name: passengers, Length: 6433, dtype: float64